nomeComp = str(input('Digite seu nome completo: '))
nome = nomeComp.split()
print('Muito prazer te conhecer!')
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu último nome é {}'.format(nome[-1]))