frase = str(input('Digite uma frase: ')).strip()
palavra = frase.upper()
print('A letra A aparece {} vezes na frase.'.format(palavra.count('A')))
print('A primeira letra A aparece na posição {}'.format(frase.find('A')+1))
print('A última letra A aparece na posição {}'.format(frase.rfind('a')+1))